### PR TITLE
change default var value in modA

### PR DESCRIPTION
**Pull request by sgmitchell**

### CODE REVIEW

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by fs-rw** [comment]
Ran Plan for 2 projects:

1. project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`
1. project: `projectB` dir: `projects/fullstory/etc/terraform/projectB` workspace: `default`

### 1. project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`
<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.a.google_storage_bucket_object.obj must be replaced
-/+ resource "google_storage_bucket_object" "obj" {
        bucket         = "stevem-tf-test-a-proja"
        content        = (sensitive value)
      ~ content_type   = "text/plain; charset=utf-8" -> (known after apply)
      ~ crc32c         = "QwQfYQ==" -> (known after apply)
      ~ detect_md5hash = "+UvkjcM2qtAE1etbr+Xddg==" -> "different hash"
      ~ id             = "stevem-tf-test-a-proja-myObj" -> (known after apply)
      ~ md5hash        = "+UvkjcM2qtAE1etbr+Xddg==" -> (known after apply)
      ~ name           = "myObj" -> "myObj2" # forces replacement
      ~ output_name    = "myObj" -> (known after apply)
      ~ self_link      = "https://www.googleapis.com/storage/v1/b/stevem-tf-test-a-proja/o/myObj" -> (known after apply)
      ~ storage_class  = "STANDARD" -> (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p projectA`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectA%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p projectA`
</details>

---
### 2. project: `projectB` dir: `projects/fullstory/etc/terraform/projectB` workspace: `default`
<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.a.google_storage_bucket_object.obj must be replaced
-/+ resource "google_storage_bucket_object" "obj" {
        bucket         = "stevem-tf-test-a-projb"
        content        = (sensitive value)
      ~ content_type   = "text/plain; charset=utf-8" -> (known after apply)
      ~ crc32c         = "QwQfYQ==" -> (known after apply)
      ~ detect_md5hash = "+UvkjcM2qtAE1etbr+Xddg==" -> "different hash"
      ~ id             = "stevem-tf-test-a-projb-myObj" -> (known after apply)
      ~ md5hash        = "+UvkjcM2qtAE1etbr+Xddg==" -> (known after apply)
      ~ name           = "myObj" -> "myObj2" # forces replacement
      ~ output_name    = "myObj" -> (known after apply)
      ~ self_link      = "https://www.googleapis.com/storage/v1/b/stevem-tf-test-a-projb/o/myObj" -> (known after apply)
      ~ storage_class  = "STANDARD" -> (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p projectB`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectB%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p projectB`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sgmitchell** [comment]
atlantis apply

**Comment by fs-rw** [comment]
Ran Apply for 2 projects:

1. project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`
1. project: `projectB` dir: `projects/fullstory/etc/terraform/projectB` workspace: `default`

### 1. project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`
**Apply Failed**: Pull request must be approved before running apply.

---
### 2. project: `projectB` dir: `projects/fullstory/etc/terraform/projectB` workspace: `default`
**Apply Failed**: Pull request must be approved before running apply.

---

**Comment by fs-rw** [comment]
**Warning**: The plan for dir: `projects/fullstory/etc/terraform/projectA` workspace: `default` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by fs-rw** [comment]
Ran Plan for 2 projects:

1. project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`
1. project: `projectB` dir: `projects/fullstory/etc/terraform/projectB` workspace: `default`

### 1. project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`
```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p projectA`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectA%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p projectA`

---
### 2. project: `projectB` dir: `projects/fullstory/etc/terraform/projectB` workspace: `default`
<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.a.google_storage_bucket_object.obj must be replaced
-/+ resource "google_storage_bucket_object" "obj" {
        bucket         = "stevem-tf-test-a-projb"
        content        = (sensitive value)
      ~ content_type   = "text/plain; charset=utf-8" -> (known after apply)
      ~ crc32c         = "QwQfYQ==" -> (known after apply)
      ~ detect_md5hash = "+UvkjcM2qtAE1etbr+Xddg==" -> "different hash"
      ~ id             = "stevem-tf-test-a-projb-myObj" -> (known after apply)
      ~ md5hash        = "+UvkjcM2qtAE1etbr+Xddg==" -> (known after apply)
      ~ name           = "myObj" -> "myObj2" # forces replacement
      ~ output_name    = "myObj" -> (known after apply)
      ~ self_link      = "https://www.googleapis.com/storage/v1/b/stevem-tf-test-a-projb/o/myObj" -> (known after apply)
      ~ storage_class  = "STANDARD" -> (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p projectB`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectB%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p projectB`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sgmitchell** [comment]
atlantis apply

**Comment by fs-rw** [comment]
Ran Apply for 2 projects:

1. project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`
1. project: `projectB` dir: `projects/fullstory/etc/terraform/projectB` workspace: `default`

### 1. project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`
```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

```

---
### 2. project: `projectB` dir: `projects/fullstory/etc/terraform/projectB` workspace: `default`
```diff
module.a.google_storage_bucket_object.obj: Destroying... [id=stevem-tf-test-a-projb-myObj]
module.a.google_storage_bucket_object.obj: Destruction complete after 1s
module.a.google_storage_bucket_object.obj: Creating...
module.a.google_storage_bucket_object.obj: Creation complete after 0s [id=stevem-tf-test-a-projb-myObj2]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

```

---

**Comment by fs-rw** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`
- dir: `projects/fullstory/etc/terraform/projectB` workspace: `default`

**Pull request merged**
