### PR TITLE
delete x

### PR DESCRIPTION
**Pull request by sgmitchell**

### CODE REVIEW

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by fs-rw** [comment]
Ran Plan for project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # google_storage_bucket_object.objX will be destroyed
- resource "google_storage_bucket_object" "objX" {
      - bucket         = "fs-ops-terraform-stevem-test" -> null
      - content        = (sensitive value)
      - content_type   = "text/plain; charset=utf-8" -> null
      - crc32c         = "sbmluA==" -> null
      - detect_md5hash = "UyevPC5MiEY+tiGacrR6eQ==" -> null
      - id             = "fs-ops-terraform-stevem-test-objInProjX" -> null
      - md5hash        = "UyevPC5MiEY+tiGacrR6eQ==" -> null
      - name           = "objInProjX" -> null
      - output_name    = "objInProjX" -> null
      - self_link      = "https://www.googleapis.com/storage/v1/b/fs-ops-terraform-stevem-test/o/objInProjX" -> null
      - storage_class  = "STANDARD" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p projectA`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectA%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p projectA`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by fs-rw** [comment]
Ran Plan for project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # google_storage_bucket_object.objX will be destroyed
- resource "google_storage_bucket_object" "objX" {
      - bucket         = "fs-ops-terraform-stevem-test" -> null
      - content        = (sensitive value)
      - content_type   = "text/plain; charset=utf-8" -> null
      - crc32c         = "sbmluA==" -> null
      - detect_md5hash = "UyevPC5MiEY+tiGacrR6eQ==" -> null
      - id             = "fs-ops-terraform-stevem-test-objInProjX" -> null
      - md5hash        = "UyevPC5MiEY+tiGacrR6eQ==" -> null
      - name           = "objInProjX" -> null
      - output_name    = "objInProjX" -> null
      - self_link      = "https://www.googleapis.com/storage/v1/b/fs-ops-terraform-stevem-test/o/objInProjX" -> null
      - storage_class  = "STANDARD" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p projectA`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectA%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p projectA`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by fs-rw** [comment]
Ran Plan for project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # google_storage_bucket_object.objX will be destroyed
- resource "google_storage_bucket_object" "objX" {
      - bucket         = "fs-ops-terraform-stevem-test" -> null
      - content        = (sensitive value)
      - content_type   = "text/plain; charset=utf-8" -> null
      - crc32c         = "sbmluA==" -> null
      - detect_md5hash = "UyevPC5MiEY+tiGacrR6eQ==" -> null
      - id             = "fs-ops-terraform-stevem-test-objInProjX" -> null
      - md5hash        = "UyevPC5MiEY+tiGacrR6eQ==" -> null
      - name           = "objInProjX" -> null
      - output_name    = "objInProjX" -> null
      - self_link      = "https://www.googleapis.com/storage/v1/b/fs-ops-terraform-stevem-test/o/objInProjX" -> null
      - storage_class  = "STANDARD" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p projectA`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectA%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p projectA`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by fs-rw** [comment]
Ran Plan for project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # google_storage_bucket_object.objX will be destroyed
- resource "google_storage_bucket_object" "objX" {
      - bucket         = "fs-ops-terraform-stevem-test" -> null
      - content        = (sensitive value)
      - content_type   = "text/plain; charset=utf-8" -> null
      - crc32c         = "sbmluA==" -> null
      - detect_md5hash = "UyevPC5MiEY+tiGacrR6eQ==" -> null
      - id             = "fs-ops-terraform-stevem-test-objInProjX" -> null
      - md5hash        = "UyevPC5MiEY+tiGacrR6eQ==" -> null
      - name           = "objInProjX" -> null
      - output_name    = "objInProjX" -> null
      - self_link      = "https://www.googleapis.com/storage/v1/b/fs-ops-terraform-stevem-test/o/objInProjX" -> null
      - storage_class  = "STANDARD" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p projectA`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectA%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p projectA`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by sgmitchell** [comment]
^^^ yay, blacklisting doesn't have spam

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by fs-rw** [comment]
Ran Plan for project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # google_storage_bucket_object.objX will be destroyed
- resource "google_storage_bucket_object" "objX" {
      - bucket         = "fs-ops-terraform-stevem-test" -> null
      - content        = (sensitive value)
      - content_type   = "text/plain; charset=utf-8" -> null
      - crc32c         = "sbmluA==" -> null
      - detect_md5hash = "UyevPC5MiEY+tiGacrR6eQ==" -> null
      - id             = "fs-ops-terraform-stevem-test-objInProjX" -> null
      - md5hash        = "UyevPC5MiEY+tiGacrR6eQ==" -> null
      - name           = "objInProjX" -> null
      - output_name    = "objInProjX" -> null
      - self_link      = "https://www.googleapis.com/storage/v1/b/fs-ops-terraform-stevem-test/o/objInProjX" -> null
      - storage_class  = "STANDARD" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p projectA`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectA%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p projectA`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sgmitchell** [comment]
atlantis apply

**Comment by fs-rw** [comment]
Ran Apply for project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

```diff
google_storage_bucket_object.objX: Destroying... [id=fs-ops-terraform-stevem-test-objInProjX]
google_storage_bucket_object.objX: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.

```

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by fs-rw** [comment]
Ran Plan for project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p projectA`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectA%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p projectA`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by fs-rw** [comment]
Ran Plan for project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p projectA`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectA%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p projectA`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sgmitchell** [comment]
atlantis apply

**Comment by fs-rw** [comment]
Ran Apply for project: `projectA` dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

```

**Comment by fs-rw** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

**Pull request closed without merging**
