### PR TITLE
Update bucket.tf

### PR DESCRIPTION
**Pull request by sgmitchell**
testing autoapprove

### CODE REVIEW

**Comment by fs-rw** [comment]
Ran Plan for dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

**Plan Failed**: This project is currently locked by an unapplied plan from pull #4. To continue, delete the lock from #4 or apply that plan and merge the pull request.

Once the lock is released, comment `atlantis plan` here to re-plan.

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by fs-rw** [comment]
Ran Plan for dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_storage_bucket_object.objX will be created
+ resource "google_storage_bucket_object" "objX" {
      + bucket         = "fs-ops-terraform-stevem-test"
      + content        = (sensitive value)
      + content_type   = (known after apply)
      + crc32c         = (known after apply)
      + detect_md5hash = "different hash"
      + id             = (known after apply)
      + md5hash        = (known after apply)
      + name           = "objInProjX"
      + output_name    = (known after apply)
      + self_link      = (known after apply)
      + storage_class  = (known after apply)
    }

  # module.a.google_storage_bucket_object.obj must be replaced
-/+ resource "google_storage_bucket_object" "obj" {
        bucket         = "stevem-tf-test-a-proja"
        content        = (sensitive value)
      ~ content_type   = "text/plain; charset=utf-8" -> (known after apply)
      ~ crc32c         = "QwQfYQ==" -> (known after apply)
      ~ detect_md5hash = "+UvkjcM2qtAE1etbr+Xddg==" -> "different hash"
      ~ id             = "stevem-tf-test-a-proja-myObj" -> (known after apply)
      ~ md5hash        = "+UvkjcM2qtAE1etbr+Xddg==" -> (known after apply)
      ~ name           = "myObj" -> "myObj2" # forces replacement
      ~ output_name    = "myObj" -> (known after apply)
      ~ self_link      = "https://www.googleapis.com/storage/v1/b/stevem-tf-test-a-proja/o/myObj" -> (known after apply)
      ~ storage_class  = "STANDARD" -> (known after apply)
    }

Plan: 2 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d projects/fullstory/etc/terraform/projectA`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectA%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d projects/fullstory/etc/terraform/projectA`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sgmitchell** [comment]
atlantis plan

**Comment by fs-rw** [comment]
Ran Plan for dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_storage_bucket_object.objX will be created
+ resource "google_storage_bucket_object" "objX" {
      + bucket         = "fs-ops-terraform-stevem-test"
      + content        = (sensitive value)
      + content_type   = (known after apply)
      + crc32c         = (known after apply)
      + detect_md5hash = "different hash"
      + id             = (known after apply)
      + md5hash        = (known after apply)
      + name           = "objInProjX"
      + output_name    = (known after apply)
      + self_link      = (known after apply)
      + storage_class  = (known after apply)
    }

  # module.a.google_storage_bucket_object.obj must be replaced
-/+ resource "google_storage_bucket_object" "obj" {
        bucket         = "stevem-tf-test-a-proja"
        content        = (sensitive value)
      ~ content_type   = "text/plain; charset=utf-8" -> (known after apply)
      ~ crc32c         = "QwQfYQ==" -> (known after apply)
      ~ detect_md5hash = "+UvkjcM2qtAE1etbr+Xddg==" -> "different hash"
      ~ id             = "stevem-tf-test-a-proja-myObj" -> (known after apply)
      ~ md5hash        = "+UvkjcM2qtAE1etbr+Xddg==" -> (known after apply)
      ~ name           = "myObj" -> "myObj2" # forces replacement
      ~ output_name    = "myObj" -> (known after apply)
      ~ self_link      = "https://www.googleapis.com/storage/v1/b/stevem-tf-test-a-proja/o/myObj" -> (known after apply)
      ~ storage_class  = "STANDARD" -> (known after apply)
    }

Plan: 2 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d projects/fullstory/etc/terraform/projectA`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.internal.ops.fs.team/lock?id=sgmitchell%252Ftf-test%252Fprojects%252Ffullstory%252Fetc%252Fterraform%252FprojectA%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d projects/fullstory/etc/terraform/projectA`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sgmitchell** [comment]
atlantis apply

**Comment by fs-rw** [comment]
Ran Apply for dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

```diff
module.a.google_storage_bucket_object.obj: Destroying... [id=stevem-tf-test-a-proja-myObj]
google_storage_bucket_object.objX: Creating...
google_storage_bucket_object.objX: Creation complete after 0s [id=fs-ops-terraform-stevem-test-objInProjX]
module.a.google_storage_bucket_object.obj: Destruction complete after 1s
module.a.google_storage_bucket_object.obj: Creating...
module.a.google_storage_bucket_object.obj: Creation complete after 0s [id=stevem-tf-test-a-proja-myObj2]

Apply complete! Resources: 2 added, 0 changed, 1 destroyed.

```

**Comment by fs-rw** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `projects/fullstory/etc/terraform/projectA` workspace: `default`

**Pull request merged**
